### ISSUE TITLE
OAS Sitepage url for custom verticals

### ISSUE THREAD

**Issue by johndhancock** [DallasMorningNews/generator-dmninteractives#11]
The url structure for the OAS sitepage url needs to be customized based on what vertical the interactive falls under. For example. OAS urls have always followed a structure of http://www.dallasnews.com/<<Desk>>/<<Section>>. 

This doesn't hold up now that sportsday and guidelive have their own verticals, and section names have changed. While a story in business or news would still follow the above format, sections in sportsday would follow the following format: 

http://sportsday.dallasnews.com/dallas-cowboys (note, not only has the parent directory changes, but the desk directory also has newer syntax than what we've previously been used to.

Guidelive is similar: http://www.guidelive.com/movies.

**Comment by achavez** [comment]
We can close this now that we're no longer using Omniture
