### ISSUE TITLE
Add "originals" directory

### ISSUE THREAD

**Issue by LayneSmith** [DallasMorningNews/generator-dmninteractives#12]
When I create custom stuff like illustrations or buttons in Photoshop and Illustrator, I like to save those as original PSD and AI files so I can preserve layers etc...

It'd be nice to have a folder I can keep all these originals in so they can travel with the project. It shouldn't be deployed as a part of the project's online presence but it should be included in the .zip file so if changes need to be made to one of the originals, it's available.

That would be swell.

**Comment by hobbes7878** [comment]
Will have it next update.
