### ISSUE TITLE
Leaflet link error: Uncaught Error: Couldn't autodetect L.Icon.Default.imagePath, set it manually.

### ISSUE THREAD

**Issue by LayneSmith** [DallasMorningNews/generator-dmninteractives#13]
Get following error on Leaflet implementation. Any workarounds available yet?

`Uncaught Error: Couldn't autodetect L.Icon.Default.imagePath, set it manually.`

**Comment by extremeweather1** [comment]
L.Icon.Default.imagePath = 'path-to-your-leaflet-images-folder';
