### ISSUE TITLE
All images are processed upon change to images directory

### ISSUE THREAD

**Issue by toxford** [DallasMorningNews/generator-dmninteractives#16]
Even if a single, non-repsonsive image is added, every file is processed. This hogs processes for several minutes.

**Comment by hobbes7878** [comment]
OK, I'm going to split up the image processing tasks. 
1. For any images added, we'll run compression and put the results in `build/images/opt`.
2. We'll watch that directory for new images and resize to the `public` dir.

Two major optimizations that should really speed up the processing: reducing the number of images we're running compression over by a factor of 5 and implementing a caching mechanism to remove unchanged files from the pipeline.

Will push with next point release.
