### ISSUE TITLE
Remove gulp killing function upon javascript error

### ISSUE THREAD

**Issue by johndhancock** [DallasMorningNews/generator-dmninteractives#21]
Please, for the love of God, remove the feature that kills gulp processes when there is a javascript error. I'd love for some sort of error notification like when there is a css error in the console. 

Restarting gulp each time, and having it open a new browser tab, is a giant pain. Open inspector windows become invalid unless I switch back to my old tab. By the end of the day, my browser looks like this: 

![image](https://cloud.githubusercontent.com/assets/2925642/17748330/7928bace-647e-11e6-87df-d85dc34dc1ef.png)

I know, I could write better javascript, but a great man once said, "Don't code for behavior," or something like that.

**Comment by achavez** [comment]
I'm closing this since the new, Browserify-ed generator shouldn't do this.
