### ISSUE TITLE
Publish .zip to test also

### ISSUE THREAD

**Issue by LayneSmith** [DallasMorningNews/generator-dmninteractives#22]
So if I'm working on a project and have only gotten as far as publishing to test, it'd be nice to have the .zip pushed as well so I can just pull down that .zip when I get home and pick up where I left off.

**Comment by hobbes7878** [comment]
I mean, I'm cool with that if that's what y'all want to do. We were sorta moving away from the zip backup b/c it gets so damn large on photo heavy projects. My initial thought is github is made for exactly your sort of problem. Could just have a repo for projects you're working on that you can access at home, though we only get so many private repos and I'm also not really wild about using github as storage for every interactive we do...

Welcoming other thoughts.

**Comment by LayneSmith** [comment]
So the objective is simply to make it as easy as possible to pull down a current copy of a project in-progress. Building a .zip with all the necessary pieces that gets published with the project to test, something we do anyway, just seemed like an easy way to do this without GitHub or selectively moving files to some cloud drive somewhere. If y'all have a better idea that accomplishes the same thing, let's do it!

**Comment by hobbes7878** [comment]
We're going to deprecate the zip file creation/transmission tasks in the next generator point release. 

Github is really the more natural solution to exactly what you're talking about, sharing project files between computers or people and managing file changes.

With our new pricing plan on github, you can keep any projects you're working on in private repositories that you'll be able to access anywhere you have interwebs. We'll give you more training on using git when we make the change.

**Comment by LayneSmith** [comment]
As long as they're private repositories, I'm totally on board with a git solution. Thanks.
