### ISSUE TITLE
Add a folder where we can keep raw files

### ISSUE THREAD

**Issue by LayneSmith** [DallasMorningNews/generator-dmninteractives#23]
So if I'm working on a graphic or illustration with lots of layers, it'd be nice if that original file could get zipped up and travel with the .zip so I can have access to it after downloading.

**Comment by hobbes7878** [comment]
See #22 on this, I think. Hopefully same solution.

**Comment by LayneSmith** [comment]
Agree that packing these files into that .zip, or whatever we decide, would be a good solution.
