### ISSUE TITLE
Incorporate gulp command into publish?

### ISSUE THREAD

**Issue by LayneSmith** [DallasMorningNews/generator-dmninteractives#24]
Would like to be able to make a fix and hit "gulp publish" without having to do just "gulp" first. For simple fixes it then launches another browser window to close, then I have to hit ctrl-C so I can then run "gulp publish" again.

For minor fixes, it'd be cool if I could just enter "gulp publish" and have it re-roll everything without the extra steps.

**Comment by achavez** [comment]
@allanjamesvestal This is current behavior for the Browserify-ed generator, correct? I checked and it is for embeddables. If so, closing.

**Comment by achavez** [comment]
Confirming this is now the behavior. Closing this.
