### ISSUE TITLE
Add signature version to default aws config

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/generator-dmninteractives#25]
For example:

```
{
  "accessKeyId": "<KEY>",
  "secretAccessKey": "<SECRET>",
  "params": {
    "Bucket": "interactives.dallasnews.com"
  },
  "signatureVersion": "v4"
}
```

**Comment by achavez** [comment]
This hasn't been changed and, it appears, there's some conflicting advice about what the `signatureVersion` should be. So rather than risk changing it and breaking something I'm going to close this for now until this creates a problem for us.
