### ISSUE TITLE
image compression levels

### ISSUE THREAD

**Issue by johndhancock** [DallasMorningNews/generator-dmninteractives#4]
Explore a different image compression library that allows for compression level on JPEGs. Current library compression levels are a little on the high-side, especially on larger image widths.

**Comment by hobbes7878** [comment]
@jdhancock88 Maybe this?

https://www.npmjs.com/package/imagemin-jpeg-recompress

**Comment by johndhancock** [comment]
@hobbes7878 Looks like that only does jpegs? Would lose out compression capability on pngs, unless I'm missing something, or we add in a separate png compression library?
