### ISSUE TITLE
'env' setting for linter config?

### ISSUE THREAD

**Issue by allanjamesvestal** [DallasMorningNews/generator-dmninteractives#41]
Should we think about adding a browser-environment setting to the `.eslintrc.json` output from the `linters` sub-generator?

The setting would look like this:

```js
{
    // . . .
    "env": {
        "browser": true
    }
    // . . .
}
```

... and would keep variables like `document` and `window` from raising `variable undefined` linting errors in Atom, even though they'll work just fine in the browser.

I'd think this could add increased sanity to the linting process, but there may be an edge case I'm missing here that would discourage this practice.

Curious to hear thoughts on this.

**Comment by achavez** [comment]
I think that'd be a great addition, @allanjamesvestal
