### ISSUE TITLE
Lint error on jquery import statement

### ISSUE THREAD

**Issue by johndhancock** [DallasMorningNews/generator-dmninteractives#46]
Get this linter error on the import statement for jquery on a generator started up on May 10, 2017
![screen shot 2017-05-11 at 12 23 33 pm](https://cloud.githubusercontent.com/assets/2925642/25962837/df33dc20-3644-11e7-913b-c3f89941c299.png)

Package.json: 
![screen shot 2017-05-11 at 12 23 44 pm](https://cloud.githubusercontent.com/assets/2925642/25962841/e54761cc-3644-11e7-8776-4fe9f7d00a56.png)

**Comment by achavez** [comment]
This _seems_ to have stopped occurring, per @jdhancock88. Closing for now, but we can reopen if necessary.
