### ISSUE TITLE
eslint plugin jsx-a11y version

### ISSUE THREAD

**Issue by arianagiorgi** [DallasMorningNews/generator-dmninteractives#53]
eslint-config-airbnb@15.0.2 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but ^6.0.2 is installed instead. 

![screen shot 2017-07-17 at 4 24 39 pm](https://user-images.githubusercontent.com/6832094/28290557-777dc300-6b0c-11e7-8e6a-844931855040.png)

**Comment by arianagiorgi** [comment]
`"devDependencies": {
    "babel-eslint": "^7.2.3",
    "babel-preset-es2015": "^6.16.0",
    "babelify": "^7.3.0",
    "browser-sync": "^2.17.5",
    "browserify": "^14.0.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.2",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "event-stream": "^3.3.4",
    "gulp": "^3.9.1",
    "gulp-awspublish": "^3.3.0",
    "gulp-confirm": "^1.0.4",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^3.1.0",
    "gulp-sourcemaps": "^2.1.1",
    "gulp-uglify": "^2.0.0",
    "run-sequence": "^1.2.2",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.7.0"
  }`

**Comment by achavez** [comment]
@arianagiorgi  I just ran into this, too. I'll do a PR today to fix.
