### ISSUE TITLE
Have all contents of JS file, or data and assets directory push to dist with gulp

### ISSUE THREAD

**Issue by johndhancock** [DallasMorningNews/generator-dmninteractives#55]
Write now, seems gulp only moves .js files in the js directory over to dist, and doesn't move the data or assets directory over at all. Meaning currently data files that are not .js files have to be moved over to dist manually.

**Comment by achavez** [comment]
The behavior on this should now track with https://github.com/DallasMorningNews/generator-dmninteractives/tree/master/generators/page/templates#whats-inside for both the embeddable and page generators.
