### ISSUE TITLE
Have +custom.js be empty?

### ISSUE THREAD

**Issue by LayneSmith** [DallasMorningNews/generator-dmninteractives#6]
Since we stitch together all the js when it builds, couldn't we remove all the slideshow and other js that's commented out by default in the existing +custom.js and just have that live in individual files that can be deleted if not needed? That way when I open custom.js it is empty. 

Plus, if somebody writes a script that's particularly useful, it could be included as a separate file with the repository and used/not-used as desired.

**Comment by johndhancock** [comment]
A good suggestion. Might be worth just taking that code out altogether and adding it to the various code cookbook entries. I'll try to wrangle that sometime this week if no one has a problem with it.

**Comment by LayneSmith** [comment]
Cookbook addition would work too, and might be easier all the way around.
