### ISSUE TITLE
Gulp error on image resize

### ISSUE THREAD

**Issue by LayneSmith** [DallasMorningNews/generator-dmninteractives#62]
Dropped an image in to `src/images` to have it resized and an error was thrown. Ran Gulp again and get the following error when starting 'resize-images'. Image is a typical 3500px wide jpeg out of PS.

Tried again with a png and got the same error, but only after the 600 px version was created.

`Error: Error: Command failed: identify: no decode delegate for this image format ' @ error/constitute.c/ReadImage/504.`

**Comment by achavez** [comment]
@LayneSmith I think (based on the presence of `identify`) that this is a GraphicsMagic/ImageMagic issue. I'd start by checking to see which you have. Run `brew ls` to see which one you have. They're interchangeable and you may have one or both.

For each one you have run `brew reinstall` (ex: `brew reinstall imagemagick`). Based on how that goes we can figure out next steps.

**Comment by achavez** [comment]
Closing this for now as Layne says the above `brew reinstall` fixed it. Let's reopen if it reoccurs
