### ISSUE TITLE
Sass integration

### ISSUE THREAD

**Issue by write-this-way** [DallasMorningNews/generator-dmninteractives#7]
Could we try to include Sass as an option for writing stylesheets? Sass includes some specific libraries (Bourbon, Neat, Refills, Susy) and mixins that are really helpful to me for rapid development. While SCSS is similar, there are things Sass can do that it cannot.

**Comment by hobbes7878** [comment]
If I include a sass compiler, can you manage all the additional libraries
on your own? (Did you try writing sass into an scss file? I thought I
did...)

**Comment by write-this-way** [comment]
Yes, if you include the compiler I can include whatever libraries I need. I did try writing Sass into an scss file. No dice.

**Comment by hobbes7878** [comment]
OK. I'll get it in there.
